# Сборка
FROM node:18-alpine as build

WORKDIR /app

# package.json
COPY src/web/frontend/package.json ./

# Зависимости
RUN npm install

# Исходный код
COPY src/web/frontend/ .

# Сборка приложения
RUN npm run build

# Продакшен
FROM nginx:alpine

# Собранное приложение
COPY --from=build /app/dist /usr/share/nginx/html

# Конфигурация nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Порт
EXPOSE 80

# Запуск nginx
CMD ["nginx", "-g", "daemon off;"]
